name: Deploy

on:
  push:
    branches: [ "master" ]
  

jobs:
  deploy:

    runs-on: ubuntu-latest

    

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t mafasa2001/vitafeast
    - echo "${{secrets.DOCKERHUB_PASSWORD}}"| docker login -u  ${{secrets.DOCKERHUB_USERNAME}} --password-stdin